name: Static analysis

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Install tools
      run: |
        sudo apt update
        sudo apt --yes install cppcheck

    - name: Static analysis
      run: |
        cppcheck --project=PictureBrowser.cppcheck --error-exitcode=1 --enable=warning,style
