name: Compile source code (MSVC)

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        targetplatform: [x86, x64]

    
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1.0.3
    
    - name: Build PictureBrowser
      run: msbuild PictureBrowser.sln /p:Platform=$env:TargetPlatform /p:Configuration=Release
      env:
        TargetPlatform: ${{ matrix.targetplatform }}
